name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install guix (We dont need full SD, just the ability to build packages is fine)
      run: sudo apt install guix

    - name: Start guix
      run: sudo systemctl restart hosted-compute-agent.service

    - name: Build packages
      run: make packages
